language: python

python:
  - 3.10

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coveralls

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test
  - ./tools/coveralls report --repo-token=$COVERALLS_REPO_TOKEN ./coverage.xml

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "RlmpNG/fLurK/lcT9hD9vVoOB+N4kV14f/7pZ+puJSpMWkLULRz5TiQ5kyTJ7/oyGCBpB9rS9tfLXw1T5cT93qelwTD3SpdCmbrMEKryDHjRmW0NlowAygK/JQ6xze7jNhLY3f3jkRa9dHdtVvCKL+ZMV1EEJK5NomX8TdhRryUVJgmJu8HnLRcYz0AFKIcw61B8abXDBxzG3lW8HrgeAm4NtvDbD5hS6I+6l/k1SRxJguCt0ALGRzWyD7OFh4gwaQMAij0EWMjAC9qu+l5aGfPbANoLAgDRsIhsdDysBp1xHweunKUUVbz0MgetpZC34fQJiYab9Hwar21aNZ0t3njEHpas6MhA6LjjUblj6QI4fHCf1zXoic2tTWiaRZ1lxlVB5oBjlnxwaVmJMdtdV6jZAdxYlCokZgLWsIuKsegwZ4zOu2Gyl0HOypzCPZuU3T8Ab0//Z/6dnxTWDWebc+pXP6Kuxl0O71JHoH1lgAJaNZgGDdDpyRIpqCcc848SiQYVFOvREAjutey+TaJE7GOBSkrE1J0+3wvfO//nalqr9Gxy2F/s4oQg2vOXwBYanUAp7qwsHbJhe+iWg89ww+V2h5s0jlKl0ZfI+VQG6xsf/NQBrYjkJJKbk5LEg6zOcp20APRmOhorHO6Z435T+GLqe5Kk3q4tIS+qjEepjC0="
  secret_access_key:
    secure: "PVqlVfQJTZjZFsuefq0tiGugWJVnDfyKjjjU/Lm//jsFAjjcXbQJ+Rqw8PqtObzbC6OdLQJ+K4Q/ighdGb99OWY5mYSIb0ad/cdGR2I6184zarX37qF+XuUTUtBst0zbjkSfpmdaQ0J5FI56nyGieX4X7Y7JBYl+fhVW6KbYrO/tEY1c7IVCB3XMdPG4q8RgnkouR11qDthijaL6dYntGli/htCeMjBdnoypHMbojz9oaJumOlm6m44dXsRTi8r8JO8K6q6KbSLrJ/CpFyxj+sG8G+Kd+haGJHf5dJVWRXvKcJ+XubLaHUM+sPZVAd0PXJ9mhIN88nBq1tueS8dp29YLITeuRH5Q0ud6dhriuPabQACtufGN+lHdva7MrWSIyYqA45V/L0nPYfNYMn7MlThfHU3gV8IoC/mYACS1FghKvgJQn+cydR9x9SwneWbgrFiiGpo1Ioyi3sbPMsg8v4W+ufIwsUS9rLbT3WUZgiMfTpQhZdV67vbUFOVjRhipa+KmyhyjWmYa1s6rvbbe/SMZodoIK+FoMQy4WFt0rEllnHxy76kO15REwmTMEepPq7RZW6j2yUQx2elKpNnMq1SDM+/YPgKZevu8MnQJRFj7XAQWjLPpC9WV2jNYrKuEVmi1u1MSc/C8LBAsDqXh9yMOvHQQ+72q6qGnFWrSm28="
  region: "us-west-2"
  app: "polls-app"
  env: "polls-env"
  bucket_name: "elasticbeanstalk-us-west-2-654654401510"
