language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coveralls

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY_ID
  region: "us-west-2"
  app: "polls-app"
  env: "polls-env"
  bucket_name: "elasticbeanstalk-us-west-2-654654401510"
