language: python

python:
  - "3.9"

install:
  - pip install 'urllib3<2.0'
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - env
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "polls-app"
  env: "polls-env"
  bucket_name: "elasticbeanstalk-us-west-2-654654401510"
  on:
    repo: gamSeier/swe1-app
    branch: main
